<a href="https://colab.research.google.com/github/ShefaliShettyy/DeepLearning/blob/main/BOW_spamornot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import spacy

In [7]:
nlp = spacy.load('en_core_web_sm') #english trained model

In [14]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [8]:
doc = nlp("Elon flew to mars yesturday. He carried biryani masala with him")
doc

Elon flew to mars yesturday. He carried biryani masala with him

In [9]:
for token in doc:
  print(token)

Elon
flew
to
mars
yesturday
.
He
carried
biryani
masala
with
him


In [13]:
#How do u print the part of speech for each of this token?
for token in doc:
  print(token,"|", token.pos, "|", token.pos_ , "|" , spacy.explain(token.pos_))

Elon | 96 | PROPN | proper noun
flew | 100 | VERB | verb
to | 85 | ADP | adposition
mars | 92 | NOUN | noun
yesturday | 92 | NOUN | noun
. | 97 | PUNCT | punctuation
He | 95 | PRON | pronoun
carried | 100 | VERB | verb
biryani | 84 | ADJ | adjective
masala | 92 | NOUN | noun
with | 85 | ADP | adposition
him | 95 | PRON | pronoun


In [15]:
#BOW

In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [19]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [20]:
# df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
def get_spam_number(x):
  if x == 'spam':
    return 1
  else:
    return 0
df['spam'] = df['Category'].apply(get_spam_number)

In [21]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Message'], df['spam'], test_size=0.2)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)
(4457,)
(1115,)


In [26]:
type(X_train)

pandas.core.series.Series

In [27]:
X_train[:4]

5173                                                 U 2.
2846           Will be out of class in a few hours. Sorry
5539                           Just sleeping..and surfing
4876    I know dat feelin had it with Pete! Wuld get w...
Name: Message, dtype: object

In [28]:
X_train[5173]

'U 2.'

In [29]:
#from sklearn we will call count vectorizer help build BOW
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values) #this will generate BOW
X_train_cv

<4457x7716 sparse matrix of type '<class 'numpy.int64'>'
	with 59001 stored elements in Compressed Sparse Row format>

In [31]:
#convert saprse matrix to numpy array
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
X_train_cv.shape #7716 unique words

(4457, 7716)

In [35]:
v.get_feature_names_out()[1000:1030]

array(['anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologetic', 'apologise',
       'apologize', 'apology', 'app', 'apparently', 'appeal', 'appear',
       'appendix', 'applebees'], dtype=object)

In [37]:
v.get_feature_names_out().shape

(7716,)

In [38]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [39]:
v.vocabulary_

{'will': 7489,
 'be': 1278,
 'out': 5011,
 'of': 4894,
 'class': 1834,
 'in': 3626,
 'few': 2809,
 'hours': 3507,
 'sorry': 6307,
 'just': 3864,
 'sleeping': 6202,
 'and': 964,
 'surfing': 6607,
 'know': 3945,
 'dat': 2169,
 'feelin': 2794,
 'had': 3290,
 'it': 3740,
 'with': 7521,
 'pete': 5176,
 'wuld': 7616,
 'get': 3114,
 'em': 2562,
 'nuther': 4863,
 'place': 5232,
 'time': 6880,
 'mayb': 4392,
 'so': 6265,
 'your': 7685,
 'telling': 6733,
 'me': 4399,
 'coulda': 2031,
 'been': 1300,
 'real': 5592,
 'valentine': 7218,
 'wasn': 7364,
 'never': 4757,
 'pick': 5204,
 'for': 2930,
 'nothing': 4833,
 'congratulations': 1965,
 'thanks': 6781,
 'to': 6909,
 'good': 3181,
 'friend': 2997,
 'have': 3356,
 'won': 7551,
 'the': 6791,
 '000': 1,
 'xmas': 7629,
 'prize': 5418,
 'claim': 1826,
 'is': 3729,
 'easy': 2507,
 'call': 1613,
 '08718726978': 144,
 'now': 4842,
 'only': 4949,
 '10p': 256,
 'per': 5149,
 'minute': 4496,
 'bt': 1543,
 'national': 4703,
 'rate': 5567,
 'you': 7681,
 'wot'

In [42]:
v.get_feature_names_out()[5805]

'ron'

In [44]:
#convert to numpy array
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [47]:
X_test_cv = v.transform(X_test)

In [51]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.99      0.93      0.96       145

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [52]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [53]:
email_counts = v.transform(emails)
model.predict(email_counts)

array([0, 1])

In [54]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [55]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [56]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.99      0.93      0.96       145

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

