<a href="https://colab.research.google.com/github/ShefaliShettyy/DeepLearning/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=500

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr) #it will print wherever the index is one

[[56, 225, 113, 295], [56, 225, 113, 45], [56, 271, 113, 321], [382, 343, 397, 367, 22], [382, 343, 397, 367, 110], [324, 56, 23, 113, 169], [364, 460, 303, 367]]


In [9]:
#number will be 0 to 500
#in sent the words have diff length
#sentence of diff size
#in Neural network sentences should be of fixed size ---> that the reason we do post and pre padding

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length= 8 #maximum size of the sentence will be 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #this will make sure it will make all the sentence 8 as shown below
print(embedded_docs)

[[  0   0   0   0  56 225 113 295]
 [  0   0   0   0  56 225 113  45]
 [  0   0   0   0  56 271 113 321]
 [  0   0   0 382 343 397 367  22]
 [  0   0   0 382 343 397 367 110]
 [  0   0   0 324  56  23 113 169]
 [  0   0   0   0 364 460 303 367]]


In [16]:
#add 0 before or after for padding
# in any nlp problem to solve these steps are to be followed

In [17]:
## 10 feature dimesnions
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length)) #embedding layer is going to work similar like word to vec
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
embedded_docs[0] #first sentence
#the glass of milk

array([  0,   0,   0,   0,  56, 225, 113, 295], dtype=int32)

In [24]:
model.predict(embedded_docs[0]) #[0]  and 10 dim [-0.04436056, -0.02320272, -0.00124726, -0.04609189,  0.00424092, 0.02445693,  0.04664831,  0.01474493,  0.00486588, -0.01601176] is smame

1/1 [==============================] - 0s 20ms/step


array([[-0.04436056, -0.02320272, -0.00124726, -0.04609189,  0.00424092,
         0.02445693,  0.04664831,  0.01474493,  0.00486588, -0.01601176],
       [-0.04436056, -0.02320272, -0.00124726, -0.04609189,  0.00424092,
         0.02445693,  0.04664831,  0.01474493,  0.00486588, -0.01601176],
       [-0.04436056, -0.02320272, -0.00124726, -0.04609189,  0.00424092,
         0.02445693,  0.04664831,  0.01474493,  0.00486588, -0.01601176],
       [-0.04436056, -0.02320272, -0.00124726, -0.04609189,  0.00424092,
         0.02445693,  0.04664831,  0.01474493,  0.00486588, -0.01601176],
       [-0.03444879,  0.04031695,  0.03431642,  0.03612012,  0.00194722,
         0.0463183 ,  0.01733564,  0.04714132, -0.01854471, -0.01173543],
       [ 0.0494437 , -0.02960121, -0.04261506, -0.03818233,  0.04456747,
         0.01504144,  0.04465559, -0.04065077,  0.00394214, -0.03005884],
       [ 0.02878283,  0.03315582, -0.00696037,  0.02271693,  0.02450397,
        -0.00162677, -0.00612855,  0.00356435

In [25]:
#now we have converted to vectors

In [26]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]